---
language: bash

os:
  - linux

services:
  - docker

stages:
  - test
  - build_deploy

jobs:
  include:
    - stage: test
      name: "AgentInfo"
      script: |
        ./agent-info.sh

    - stage: test
      name: "YamlLint"
      script: |
        docker run --rm -w /repo -v $(pwd):/repo -t alpine:3.13 /bin/sh -c '
          apk add --no-cache py-pip python3 bash
          pip3 install yamllint
          yamllint .
        '

    - stage: test
      name: "ShellCheck"
      script: |
        docker run --rm -w /repo -v $(pwd):/repo -t alpine:3.13 /bin/sh -c '
          apk add --no-cache shellcheck bash
          shellcheck $(find . -type f -name "*.sh" |  tr '\n' ' ')
        '
    - stage: build_deploy
      name: "Build Fedora and Deploy to GitHub Releases"
      script: ./build_in_docker.sh
      deploy:
        provider: releases
        api_key: "$GITHUB_TOKEN"
        file_glob: true
        file: "fedora-kickstarts/output_zip/*"
        skip_cleanup: true
        on:
          tags: true
